CREATE TABLE [dbo].[AspNetUsers] (
    [Id]                       NVARCHAR (128) NOT NULL,
    [Email]                    NVARCHAR (256) NULL,
    [EmailConfirmed]           BIT            NOT NULL,
    [PasswordHash]             NVARCHAR (MAX) NULL,
    [SecurityStamp]            NVARCHAR (MAX) NULL,
    [PhoneNumber]              NVARCHAR (MAX) NULL,
    [PhoneNumberConfirmed]     BIT            NOT NULL,
    [TwoFactorEnabled]         BIT            NOT NULL,
    [LockoutEndDateUtc]        DATETIME       NULL,
    [LockoutEnabled]           BIT            NOT NULL,
    [AccessFailedCount]        INT            NOT NULL,
    [UserName]                 NVARCHAR (256) NOT NULL,
    [ResetPasswordToken]       NVARCHAR (550) NULL,
    [PasswordVerifyToken]      NVARCHAR (550) NULL,
    [PasswordTokenExpiredDate] DATETIME       NULL,
    [PhoneVerifyToken]         NVARCHAR (550) NULL,
    [TokenExpiredDate]         DATETIME       NULL,
    [MembershipType]           BIT            NULL,
    [Address]                  NVARCHAR (550) NULL,
    [CountryId]                INT            NULL,
    [CityId]                   INT            NULL,
    [IsActive]                 BIT            NULL,
    [CreationTime]             DATETIME       NULL,
    [LastSeen]                 DATETIME       NULL,
    [Image]                    NVARCHAR (550) NULL,
    [CanAddAds]                BIT            NULL,
    [Phone]                    NVARCHAR (50)  NULL,
    [FreeAdCount]              INT            NULL,
    [Type]                     TINYINT        NULL,
    [Name]                     NVARCHAR (350) NULL,
    [NotificationToken]        NVARCHAR (MAX) NULL,
    [FirstName]                NVARCHAR (MAX) NULL,
    [SecondName]               NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_dbo.AspNetUsers] PRIMARY KEY CLUSTERED ([Id] ASC)
);

