//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cigarette.Enterprise.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CEO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CEO()
        {
            this.CEOAddEditRequests = new HashSet<CEOAddEditRequest>();
            this.News = new HashSet<News>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string LinkedIn { get; set; }
        public string Twitter { get; set; }
        public string SnapChat { get; set; }
        public string CVNote { get; set; }
        public string ImageUrl { get; set; }
        public string CVDescription { get; set; }
        public string Company { get; set; }
        public string Email { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Views { get; set; }
        public string CVUrl { get; set; }
        public Nullable<int> DaleelRef { get; set; }
        public string Summary { get; set; }
        public string Slug { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CEOAddEditRequest> CEOAddEditRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News> News { get; set; }
    }
}
