//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cigarette.Enterprise.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CEOAddEditRequest
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string CVDescription { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> CEOId { get; set; }
        public string CVUrl { get; set; }
        public string NationalIdImageUrl { get; set; }
    
        public virtual CEO CEO { get; set; } 
    }
}
