//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cigarette.Enterprise.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public string imageUrl { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Tags { get; set; }
        public Nullable<long> CeoId { get; set; }
        public string Slug { get; set; }
        public Nullable<int> OldNewsRef { get; set; }
        public Nullable<byte> Category { get; set; }
        public string Language { get; set; }
    
        public virtual CEO CEO { get; set; }
    }
}
