//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cigarette.Enterprise.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SaudiceosEntities : DbContext
    {
        public SaudiceosEntities()
            : base("name=SaudiceosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<IndividualOpportunityDiscovery> IndividualOpportunityDiscoveries { get; set; }
        public virtual DbSet<KnowledgeCenter> KnowledgeCenters { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<CompanyAttractRequest> CompanyAttractRequests { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<CEO> CEOs { get; set; }
        public virtual DbSet<CEOAddEditRequest> CEOAddEditRequests { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
    
        public virtual int IncreaseViews(Nullable<int> id, Nullable<int> amount, Nullable<int> entity)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(int));
    
            var entityParameter = entity.HasValue ?
                new ObjectParameter("entity", entity) :
                new ObjectParameter("entity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("IncreaseViews", idParameter, amountParameter, entityParameter);
        }
    }
}
