//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cigarette.Enterprise.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public string SiteName { get; set; }
        public string SiteEmail { get; set; }
        public string SiteFax { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string FooterSentence { get; set; }
        public string SiteKeywords { get; set; }
        public string SiteDescription { get; set; }
        public string SiteFacebook { get; set; }
        public string SiteTwitter { get; set; }
        public string SiteSnapchat { get; set; }
        public string SiteFlicker { get; set; }
        public string SiteGoogle { get; set; }
        public string SiteLinkedIn { get; set; }
        public string SiteInstagram { get; set; }
        public string SiteViemo { get; set; }
        public string ShareCode { get; set; }
        public string GoogleAnalytics { get; set; }
        public string GoogleMaps { get; set; }
        public string SiteHomeDescription { get; set; }
        public string TermsOfUse { get; set; }
        public string Disclaimer { get; set; }
        public string AboutUs { get; set; }
    }
}
