//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cigarette.Enterprise.ResourceManager.LanguagesResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CategoryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cigarette.Enterprise.ResourceManager.LanguagesResourceFiles.CategoryResource", typeof(CategoryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category Details.
        /// </summary>
        public static string AdminCategoryEditCategoryTitle {
            get {
                return ResourceManager.GetString("AdminCategoryEditCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string AdminNewCartgoryAdd {
            get {
                return ResourceManager.GetString("AdminNewCartgoryAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Description.
        /// </summary>
        public static string AdminNewCategoryArabicDes {
            get {
                return ResourceManager.GetString("AdminNewCategoryArabicDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string AdminNewCategoryChangeLogo {
            get {
                return ResourceManager.GetString("AdminNewCategoryChangeLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Description.
        /// </summary>
        public static string AdminNewCategoryEngliishDes {
            get {
                return ResourceManager.GetString("AdminNewCategoryEngliishDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Details.
        /// </summary>
        public static string AdminNewCategoryFields {
            get {
                return ResourceManager.GetString("AdminNewCategoryFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string AdminNewCategoryIsActive {
            get {
                return ResourceManager.GetString("AdminNewCategoryIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Parent Category.
        /// </summary>
        public static string AdminNewCategoryIsParent {
            get {
                return ResourceManager.GetString("AdminNewCategoryIsParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Not Be Empty.
        /// </summary>
        public static string AdminNewCategoryNullError {
            get {
                return ResourceManager.GetString("AdminNewCategoryNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnglishDescription.
        /// </summary>
        public static string AdminNewCategoryParentName {
            get {
                return ResourceManager.GetString("AdminNewCategoryParentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string AdminNewCategoryRemoveLogo {
            get {
                return ResourceManager.GetString("AdminNewCategoryRemoveLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Parent Category.
        /// </summary>
        public static string AdminNewCategorySelectCategory {
            get {
                return ResourceManager.GetString("AdminNewCategorySelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Logo.
        /// </summary>
        public static string AdminNewCategorySelectLogo {
            get {
                return ResourceManager.GetString("AdminNewCategorySelectLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string AdminNewCategorySubmit {
            get {
                return ResourceManager.GetString("AdminNewCategorySubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Type.
        /// </summary>
        public static string Category_Type {
            get {
                return ResourceManager.GetString("Category_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Category.
        /// </summary>
        public static string Commercial_Category {
            get {
                return ResourceManager.GetString("Commercial_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Commercial Category.
        /// </summary>
        public static string Not_Commercial_Category {
            get {
                return ResourceManager.GetString("Not_Commercial_Category", resourceCulture);
            }
        }
    }
}
