//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cigarette.Enterprise.ResourceManager.LanguagesResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cigarette.Enterprise.ResourceManager.LanguagesResourceFiles.HomeResource", typeof(HomeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Contact Info.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Country Contact Info.
        /// </summary>
        public static string AboutCountryEdit {
            get {
                return ResourceManager.GetString("AboutCountryEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Plus Url.
        /// </summary>
        public static string AboutGooglePlus {
            get {
                return ResourceManager.GetString("AboutGooglePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number 2.
        /// </summary>
        public static string AboutPhone2 {
            get {
                return ResourceManager.GetString("AboutPhone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Contact Info.
        /// </summary>
        public static string aboutTitle {
            get {
                return ResourceManager.GetString("aboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us Arabic.
        /// </summary>
        public static string AboutUsArabic {
            get {
                return ResourceManager.GetString("AboutUsArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string AboutusEmail {
            get {
                return ResourceManager.GetString("AboutusEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us English.
        /// </summary>
        public static string AboutUsEnglish {
            get {
                return ResourceManager.GetString("AboutUsEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Page.
        /// </summary>
        public static string AboutusFaceboo {
            get {
                return ResourceManager.GetString("AboutusFaceboo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram Account.
        /// </summary>
        public static string AboutusInstagram {
            get {
                return ResourceManager.GetString("AboutusInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number 1.
        /// </summary>
        public static string AboutusPhone {
            get {
                return ResourceManager.GetString("AboutusPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy &amp; Policy Arabic.
        /// </summary>
        public static string AboutusPrivacyArabic {
            get {
                return ResourceManager.GetString("AboutusPrivacyArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy &amp; Policy English.
        /// </summary>
        public static string AboutusPrivacyEnglish {
            get {
                return ResourceManager.GetString("AboutusPrivacyEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms&amp;Conditions Arabic.
        /// </summary>
        public static string AboutusTermsArabic {
            get {
                return ResourceManager.GetString("AboutusTermsArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms&amp;Conditions English.
        /// </summary>
        public static string AboutusTermsEnglish {
            get {
                return ResourceManager.GetString("AboutusTermsEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Info.
        /// </summary>
        public static string AboutusTitle {
            get {
                return ResourceManager.GetString("AboutusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Account.
        /// </summary>
        public static string AboutusTwitter {
            get {
                return ResourceManager.GetString("AboutusTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube Channel.
        /// </summary>
        public static string AboutusYoutube {
            get {
                return ResourceManager.GetString("AboutusYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abuse Reports.
        /// </summary>
        public static string Abuse_Reports {
            get {
                return ResourceManager.GetString("Abuse_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string AbuseReport_Message {
            get {
                return ResourceManager.GetString("AbuseReport_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string AbuseReport_Reason {
            get {
                return ResourceManager.GetString("AbuseReport_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registeration on Saudiceos considered accepting for.
        /// </summary>
        public static string accept_agreement {
            get {
                return ResourceManager.GetString("accept_agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Details.
        /// </summary>
        public static string AdAdditionalDetails {
            get {
                return ResourceManager.GetString("AdAdditionalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Favorite.
        /// </summary>
        public static string AddFavorite {
            get {
                return ResourceManager.GetString("AddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Admin.
        /// </summary>
        public static string AddNewAdmin {
            get {
                return ResourceManager.GetString("AddNewAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Ploicy in Arabic.
        /// </summary>
        public static string admin_privacy_policy_ar {
            get {
                return ResourceManager.GetString("admin_privacy_policy_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy in English.
        /// </summary>
        public static string admin_privacy_policy_en {
            get {
                return ResourceManager.GetString("admin_privacy_policy_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safty Rules in Arabic.
        /// </summary>
        public static string admin_safty_rules_ar {
            get {
                return ResourceManager.GetString("admin_safty_rules_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safty Rules in English.
        /// </summary>
        public static string admin_safty_rules_en {
            get {
                return ResourceManager.GetString("admin_safty_rules_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use in Arabic .
        /// </summary>
        public static string admin_term_use_ar {
            get {
                return ResourceManager.GetString("admin_term_use_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use in English.
        /// </summary>
        public static string admin_term_use_en {
            get {
                return ResourceManager.GetString("admin_term_use_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Bundle.
        /// </summary>
        public static string AdminAddNewBundle {
            get {
                return ResourceManager.GetString("AdminAddNewBundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Category.
        /// </summary>
        public static string AdminAddNewCategory {
            get {
                return ResourceManager.GetString("AdminAddNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string AdminAddNewCategoryLogo {
            get {
                return ResourceManager.GetString("AdminAddNewCategoryLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Specification.
        /// </summary>
        public static string AdminAddNewSpecification {
            get {
                return ResourceManager.GetString("AdminAddNewSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New State.
        /// </summary>
        public static string AdminAddNewState {
            get {
                return ResourceManager.GetString("AdminAddNewState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Ad.
        /// </summary>
        public static string AdminAdsAddNew {
            get {
                return ResourceManager.GetString("AdminAdsAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string AdminAdsCategory {
            get {
                return ResourceManager.GetString("AdminAdsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Category.
        /// </summary>
        public static string AdminAdsChooseCategory {
            get {
                return ResourceManager.GetString("AdminAdsChooseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Country.
        /// </summary>
        public static string AdminAdsChooseCountry {
            get {
                return ResourceManager.GetString("AdminAdsChooseCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string AdminAdsCountry {
            get {
                return ResourceManager.GetString("AdminAdsCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string AdminAdsCreationDate {
            get {
                return ResourceManager.GetString("AdminAdsCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Description.
        /// </summary>
        public static string AdminAdsDescription {
            get {
                return ResourceManager.GetString("AdminAdsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Details.
        /// </summary>
        public static string AdminAdsDetails {
            get {
                return ResourceManager.GetString("AdminAdsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string AdminAdsEndDate {
            get {
                return ResourceManager.GetString("AdminAdsEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Image.
        /// </summary>
        public static string AdminAdsImage {
            get {
                return ResourceManager.GetString("AdminAdsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Link.
        /// </summary>
        public static string AdminAdsLink {
            get {
                return ResourceManager.GetString("AdminAdsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Ads List.
        /// </summary>
        public static string AdminAdsList {
            get {
                return ResourceManager.GetString("AdminAdsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Count.
        /// </summary>
        public static string AdminAdsNotification {
            get {
                return ResourceManager.GetString("AdminAdsNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AdminAdsStatus {
            get {
                return ResourceManager.GetString("AdminAdsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Type.
        /// </summary>
        public static string AdminAdsType {
            get {
                return ResourceManager.GetString("AdminAdsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between Ads.
        /// </summary>
        public static string AdminAdsTypeInBetween {
            get {
                return ResourceManager.GetString("AdminAdsTypeInBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        public static string AdminAdsTypeOffer {
            get {
                return ResourceManager.GetString("AdminAdsTypeOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup.
        /// </summary>
        public static string AdminAdsTypePopup {
            get {
                return ResourceManager.GetString("AdminAdsTypePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        public static string AdminAdsTypeSlider {
            get {
                return ResourceManager.GetString("AdminAdsTypeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string AdminBundleActivate {
            get {
                return ResourceManager.GetString("AdminBundleActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De Activate.
        /// </summary>
        public static string AdminBundleDeActivate {
            get {
                return ResourceManager.GetString("AdminBundleDeActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Category.
        /// </summary>
        public static string AdminCategoryAddCategory {
            get {
                return ResourceManager.GetString("AdminCategoryAddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string AdminCategoryAddCategoryChooseMessage {
            get {
                return ResourceManager.GetString("AdminCategoryAddCategoryChooseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string AdminCategoryAddCategoryCreateButton {
            get {
                return ResourceManager.GetString("AdminCategoryAddCategoryCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories List For.
        /// </summary>
        public static string AdminCategoryCountryCategoriesList {
            get {
                return ResourceManager.GetString("AdminCategoryCountryCategoriesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories List.
        /// </summary>
        public static string AdminCategoryCtegories {
            get {
                return ResourceManager.GetString("AdminCategoryCtegories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Details.
        /// </summary>
        public static string AdminCategoryDetails {
            get {
                return ResourceManager.GetString("AdminCategoryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Details.
        /// </summary>
        public static string AdminCategoryDetailsA {
            get {
                return ResourceManager.GetString("AdminCategoryDetailsA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string AdminCategoryDetailsTab {
            get {
                return ResourceManager.GetString("AdminCategoryDetailsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category List.
        /// </summary>
        public static string AdminCategoryListTitle {
            get {
                return ResourceManager.GetString("AdminCategoryListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Specifications.
        /// </summary>
        public static string AdminCategorySpecificationDetailsTab {
            get {
                return ResourceManager.GetString("AdminCategorySpecificationDetailsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Specifications.
        /// </summary>
        public static string AdminCategorySpecifications {
            get {
                return ResourceManager.GetString("AdminCategorySpecifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New City.
        /// </summary>
        public static string AdminCityAddNewCity {
            get {
                return ResourceManager.GetString("AdminCityAddNewCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities List.
        /// </summary>
        public static string AdminCityCities {
            get {
                return ResourceManager.GetString("AdminCityCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities For.
        /// </summary>
        public static string AdminCityCountryCities {
            get {
                return ResourceManager.GetString("AdminCityCountryCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Details.
        /// </summary>
        public static string AdminCityDetails {
            get {
                return ResourceManager.GetString("AdminCityDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States List.
        /// </summary>
        public static string AdminCityStates {
            get {
                return ResourceManager.GetString("AdminCityStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Country.
        /// </summary>
        public static string AdminCountryAddCountry {
            get {
                return ResourceManager.GetString("AdminCountryAddCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Details.
        /// </summary>
        public static string AdminCountryCountryDetails {
            get {
                return ResourceManager.GetString("AdminCountryCountryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries List.
        /// </summary>
        public static string AdminCountryCountrylist {
            get {
                return ResourceManager.GetString("AdminCountryCountrylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Country Details.
        /// </summary>
        public static string AdminCountryEditCountryTitle {
            get {
                return ResourceManager.GetString("AdminCountryEditCountryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads Count to delete.
        /// </summary>
        public static string AdminCountToDelete {
            get {
                return ResourceManager.GetString("AdminCountToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days to delete.
        /// </summary>
        public static string AdminDaysToDelete {
            get {
                return ResourceManager.GetString("AdminDaysToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Bundle Details.
        /// </summary>
        public static string AdminEditBundleTitle {
            get {
                return ResourceManager.GetString("AdminEditBundleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string AdminFalse {
            get {
                return ResourceManager.GetString("AdminFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins List.
        /// </summary>
        public static string AdminList {
            get {
                return ResourceManager.GetString("AdminList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter any Username Or Passwod.
        /// </summary>
        public static string AdminLoginPageAlertMessage {
            get {
                return ResourceManager.GetString("AdminLoginPageAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AdminLoginPageCancel {
            get {
                return ResourceManager.GetString("AdminLoginPageCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Passwod.
        /// </summary>
        public static string AdminLoginPageForgetPassword {
            get {
                return ResourceManager.GetString("AdminLoginPageForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Login Page.
        /// </summary>
        public static string AdminLoginPageHeader {
            get {
                return ResourceManager.GetString("AdminLoginPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string AdminLoginPagePassword {
            get {
                return ResourceManager.GetString("AdminLoginPagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me ?.
        /// </summary>
        public static string AdminLoginPageRemmberMe {
            get {
                return ResourceManager.GetString("AdminLoginPageRemmberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your e-mail address below to reset your password..
        /// </summary>
        public static string AdminLoginPageResetPasswordMessage {
            get {
                return ResourceManager.GetString("AdminLoginPageResetPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string AdminLoginPageSubmit {
            get {
                return ResourceManager.GetString("AdminLoginPageSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string AdminLoginPageUserName {
            get {
                return ResourceManager.GetString("AdminLoginPageUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Successfully.
        /// </summary>
        public static string AdminMessagesAddedSuccessfully {
            get {
                return ResourceManager.GetString("AdminMessagesAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Happened.
        /// </summary>
        public static string AdminMessagesErrorHappened {
            get {
                return ResourceManager.GetString("AdminMessagesErrorHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Select.
        /// </summary>
        public static string AdminMultiSelectDropdonwList {
            get {
                return ResourceManager.GetString("AdminMultiSelectDropdonwList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AdminNavigationAbout {
            get {
                return ResourceManager.GetString("AdminNavigationAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Admins.
        /// </summary>
        public static string AdminNavigationAdmins {
            get {
                return ResourceManager.GetString("AdminNavigationAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisements.
        /// </summary>
        public static string AdminNavigationAdsSetting {
            get {
                return ResourceManager.GetString("AdminNavigationAdsSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string AdminNavigationAdvs {
            get {
                return ResourceManager.GetString("AdminNavigationAdvs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Advs.
        /// </summary>
        public static string AdminNavigationFeatures {
            get {
                return ResourceManager.GetString("AdminNavigationFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string AdminNavigationHome {
            get {
                return ResourceManager.GetString("AdminNavigationHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Issues.
        /// </summary>
        public static string AdminNavigationUserIssues {
            get {
                return ResourceManager.GetString("AdminNavigationUserIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users .
        /// </summary>
        public static string AdminNavigationUsersSetting {
            get {
                return ResourceManager.GetString("AdminNavigationUsersSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads Count.
        /// </summary>
        public static string AdminNewBundleAdsCount {
            get {
                return ResourceManager.GetString("AdminNewBundleAdsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads Cost.
        /// </summary>
        public static string AdminNewBundleCost {
            get {
                return ResourceManager.GetString("AdminNewBundleCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string AdminNewBundleCountry {
            get {
                return ResourceManager.GetString("AdminNewBundleCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle List.
        /// </summary>
        public static string AdminNewBundleList {
            get {
                return ResourceManager.GetString("AdminNewBundleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string AdminNewBundleMaxPeriod {
            get {
                return ResourceManager.GetString("AdminNewBundleMaxPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string AdminNewBundleMinPeriod {
            get {
                return ResourceManager.GetString("AdminNewBundleMinPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Bundle.
        /// </summary>
        public static string AdminNewBundleTitle {
            get {
                return ResourceManager.GetString("AdminNewBundleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SubCategory.
        /// </summary>
        public static string AdminNewCategoryAddSubCategory {
            get {
                return ResourceManager.GetString("AdminNewCategoryAddSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string AdminNewCityNameAr {
            get {
                return ResourceManager.GetString("AdminNewCityNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string AdminNewCityNameEn {
            get {
                return ResourceManager.GetString("AdminNewCityNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string AdminNewCitySubmit {
            get {
                return ResourceManager.GetString("AdminNewCitySubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string AdminNewCountryCurrency {
            get {
                return ResourceManager.GetString("AdminNewCountryCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Ad Cost.
        /// </summary>
        public static string AdminNewCountryFeaturedAdCost {
            get {
                return ResourceManager.GetString("AdminNewCountryFeaturedAdCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag.
        /// </summary>
        public static string AdminNewCountryFlag {
            get {
                return ResourceManager.GetString("AdminNewCountryFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Ad Count.
        /// </summary>
        public static string AdminNewCountryFreeAdCounts {
            get {
                return ResourceManager.GetString("AdminNewCountryFreeAdCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Country.
        /// </summary>
        public static string AdminNewCountryHeader {
            get {
                return ResourceManager.GetString("AdminNewCountryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string AdminNewCountryIsActive {
            get {
                return ResourceManager.GetString("AdminNewCountryIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string AdminNewCountryLanguage {
            get {
                return ResourceManager.GetString("AdminNewCountryLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string AdminNewCountryNameAr {
            get {
                return ResourceManager.GetString("AdminNewCountryNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string AdminNewCountryNameEn {
            get {
                return ResourceManager.GetString("AdminNewCountryNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AdminNewSpecificationAddNew {
            get {
                return ResourceManager.GetString("AdminNewSpecificationAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string AdminNewSpecificationAddOptions {
            get {
                return ResourceManager.GetString("AdminNewSpecificationAddOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Filtering.
        /// </summary>
        public static string AdminNewSpecificationAllowFiltering {
            get {
                return ResourceManager.GetString("AdminNewSpecificationAllowFiltering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string AdminNewSpecificationArabicName {
            get {
                return ResourceManager.GetString("AdminNewSpecificationArabicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string AdminNewSpecificationCategoryName {
            get {
                return ResourceManager.GetString("AdminNewSpecificationCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification Details.
        /// </summary>
        public static string AdminNewSpecificationDetails {
            get {
                return ResourceManager.GetString("AdminNewSpecificationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string AdminNewSpecificationDisplayOrder {
            get {
                return ResourceManager.GetString("AdminNewSpecificationDisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string AdminNewSpecificationEnglishName {
            get {
                return ResourceManager.GetString("AdminNewSpecificationEnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not be empty.
        /// </summary>
        public static string AdminNewSpecificationErrorMessage {
            get {
                return ResourceManager.GetString("AdminNewSpecificationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Specification.
        /// </summary>
        public static string AdminNewSpecificationFormTitle {
            get {
                return ResourceManager.GetString("AdminNewSpecificationFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string AdminNewSpecificationID {
            get {
                return ResourceManager.GetString("AdminNewSpecificationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Specification Option Details.
        /// </summary>
        public static string AdminNewSpecificationOption {
            get {
                return ResourceManager.GetString("AdminNewSpecificationOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Specification Option.
        /// </summary>
        public static string AdminNewSpecificationOptionHeader {
            get {
                return ResourceManager.GetString("AdminNewSpecificationOptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AdminNewSpecificationOptionsAddNew {
            get {
                return ResourceManager.GetString("AdminNewSpecificationOptionsAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string AdminNewSpecificationRequired {
            get {
                return ResourceManager.GetString("AdminNewSpecificationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification Type.
        /// </summary>
        public static string AdminNewSpecificationType {
            get {
                return ResourceManager.GetString("AdminNewSpecificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New State.
        /// </summary>
        public static string AdminNewStateAdd {
            get {
                return ResourceManager.GetString("AdminNewStateAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string AdminNewStateNameAr {
            get {
                return ResourceManager.GetString("AdminNewStateNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string AdminNewStateNameEn {
            get {
                return ResourceManager.GetString("AdminNewStateNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to search all.
        /// </summary>
        public static string AdminSearchForAll {
            get {
                return ResourceManager.GetString("AdminSearchForAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin List.
        /// </summary>
        public static string AdminsList {
            get {
                return ResourceManager.GetString("AdminsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification Options.
        /// </summary>
        public static string AdminSpecificationOptions {
            get {
                return ResourceManager.GetString("AdminSpecificationOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options List.
        /// </summary>
        public static string AdminSpecificationOptionsList {
            get {
                return ResourceManager.GetString("AdminSpecificationOptionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepcifications.
        /// </summary>
        public static string AdminSpecificationsList {
            get {
                return ResourceManager.GetString("AdminSpecificationsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Categories.
        /// </summary>
        public static string AdminSubCategoryDetailsTab {
            get {
                return ResourceManager.GetString("AdminSubCategoryDetailsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string AdminTableHeaderCurrency {
            get {
                return ResourceManager.GetString("AdminTableHeaderCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag.
        /// </summary>
        public static string AdminTableHeaderFlag {
            get {
                return ResourceManager.GetString("AdminTableHeaderFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string AdminTableHeaderLanguage {
            get {
                return ResourceManager.GetString("AdminTableHeaderLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not be null.
        /// </summary>
        public static string AdminTextFieldValidationMessage {
            get {
                return ResourceManager.GetString("AdminTextFieldValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string AdminTrue {
            get {
                return ResourceManager.GetString("AdminTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string AdPrice {
            get {
                return ResourceManager.GetString("AdPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string AdsCost {
            get {
                return ResourceManager.GetString("AdsCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string AdsCountryName {
            get {
                return ResourceManager.GetString("AdsCountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AdsDescription {
            get {
                return ResourceManager.GetString("AdsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string AdsDuration {
            get {
                return ResourceManager.GetString("AdsDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string AdsEndDate {
            get {
                return ResourceManager.GetString("AdsEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string AdsFree {
            get {
                return ResourceManager.GetString("AdsFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Link.
        /// </summary>
        public static string AdsLink {
            get {
                return ResourceManager.GetString("AdsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Owner.
        /// </summary>
        public static string AdsOwner {
            get {
                return ResourceManager.GetString("AdsOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string AdsPhone {
            get {
                return ResourceManager.GetString("AdsPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string AdsStartDate {
            get {
                return ResourceManager.GetString("AdsStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Type.
        /// </summary>
        public static string AdsType {
            get {
                return ResourceManager.GetString("AdsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string AdsViews {
            get {
                return ResourceManager.GetString("AdsViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisements.
        /// </summary>
        public static string AdvertisementList {
            get {
                return ResourceManager.GetString("AdvertisementList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as.
        /// </summary>
        public static string asd {
            get {
                return ResourceManager.GetString("asd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can not Feature More Than One Ad In 24 Hour.
        /// </summary>
        public static string CannotFeatureMoreThanOneAddIn24Hour {
            get {
                return ResourceManager.GetString("CannotFeatureMoreThanOneAddIn24Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Ads.
        /// </summary>
        public static string CommercailAds {
            get {
                return ResourceManager.GetString("CommercailAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Website.
        /// </summary>
        public static string CommVisitWebsite {
            get {
                return ResourceManager.GetString("CommVisitWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your message.
        /// </summary>
        public static string contact_message {
            get {
                return ResourceManager.GetString("contact_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Add your message.
        /// </summary>
        public static string contactus_please_add_message {
            get {
                return ResourceManager.GetString("contactus_please_add_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name Not Null.
        /// </summary>
        public static string CountryNameNotNull {
            get {
                return ResourceManager.GetString("CountryNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButtonTitle {
            get {
                return ResourceManager.GetString("DeleteButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailsButtonTitle {
            get {
                return ResourceManager.GetString("DetailsButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Admin Details.
        /// </summary>
        public static string EditAdminDetails {
            get {
                return ResourceManager.GetString("EditAdminDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButtonTitle {
            get {
                return ResourceManager.GetString("EditButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email invalid.
        /// </summary>
        public static string email_invalid {
            get {
                return ResourceManager.GetString("email_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Question.
        /// </summary>
        public static string FaqAddNew {
            get {
                return ResourceManager.GetString("FaqAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Arabic.
        /// </summary>
        public static string FaqAnswerAr {
            get {
                return ResourceManager.GetString("FaqAnswerAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer English.
        /// </summary>
        public static string FaqAnswerEn {
            get {
                return ResourceManager.GetString("FaqAnswerEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Arabic.
        /// </summary>
        public static string FaqQuestionAe {
            get {
                return ResourceManager.GetString("FaqQuestionAe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question English.
        /// </summary>
        public static string FaqQuestionEn {
            get {
                return ResourceManager.GetString("FaqQuestionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQs.
        /// </summary>
        public static string FaqTitile {
            get {
                return ResourceManager.GetString("FaqTitile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature.
        /// </summary>
        public static string Feature {
            get {
                return ResourceManager.GetString("Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Ad Will Deduct Two Free Ads.
        /// </summary>
        public static string FeatureAdWillDeductTwoFreeAds {
            get {
                return ResourceManager.GetString("FeatureAdWillDeductTwoFreeAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Advertisement List.
        /// </summary>
        public static string FeaturedAdsList {
            get {
                return ResourceManager.GetString("FeaturedAdsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Ads Balance.
        /// </summary>
        public static string FreeAdsBalance {
            get {
                return ResourceManager.GetString("FreeAdsBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Menu.
        /// </summary>
        public static string HasHorizontalMenu {
            get {
                return ResourceManager.GetString("HasHorizontalMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Do Not Have Free Ads.
        /// </summary>
        public static string HasNoFreeAds {
            get {
                return ResourceManager.GetString("HasNoFreeAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_ {
            get {
                return ResourceManager.GetString("Home_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctegories.
        /// </summary>
        public static string HomeHeaderCategoriesLink {
            get {
                return ResourceManager.GetString("HomeHeaderCategoriesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string HomeHeaderFavoriteLink {
            get {
                return ResourceManager.GetString("HomeHeaderFavoriteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string HomeHeaderHomeLink {
            get {
                return ResourceManager.GetString("HomeHeaderHomeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string HomeHeaderMessagesLink {
            get {
                return ResourceManager.GetString("HomeHeaderMessagesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Ad Category.
        /// </summary>
        public static string IsCommercialCategory {
            get {
                return ResourceManager.GetString("IsCommercialCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nogitable.
        /// </summary>
        public static string IsNogetable {
            get {
                return ResourceManager.GetString("IsNogetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisment Liked Successfully.
        /// </summary>
        public static string LikedSuccessfully {
            get {
                return ResourceManager.GetString("LikedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login To Your Account.
        /// </summary>
        public static string LoginPageHeader {
            get {
                return ResourceManager.GetString("LoginPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudiceos | Login Page.
        /// </summary>
        public static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Admins.
        /// </summary>
        public static string NavigationCountryAdmins {
            get {
                return ResourceManager.GetString("NavigationCountryAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Ads Found.
        /// </summary>
        public static string NoAdsFound {
            get {
                return ResourceManager.GetString("NoAdsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have Free Ads Balance .
        /// </summary>
        public static string NoFreeAdsBalanceFound {
            get {
                return ResourceManager.GetString("NoFreeAdsBalanceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Wrong.
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPeration Done Successfully.
        /// </summary>
        public static string OperationSuccess {
            get {
                return ResourceManager.GetString("OperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Ad.
        /// </summary>
        public static string RemoveAd {
            get {
                return ResourceManager.GetString("RemoveAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Favorite.
        /// </summary>
        public static string RemoveFavorite {
            get {
                return ResourceManager.GetString("RemoveFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string ReportAd {
            get {
                return ResourceManager.GetString("ReportAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        public static string SmsCountryCode {
            get {
                return ResourceManager.GetString("SmsCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Country Sms Gateway Details.
        /// </summary>
        public static string SmsEdit {
            get {
                return ResourceManager.GetString("SmsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SmsPassword {
            get {
                return ResourceManager.GetString("SmsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sms Gateways.
        /// </summary>
        public static string SmsTitle {
            get {
                return ResourceManager.GetString("SmsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string SmsUserName {
            get {
                return ResourceManager.GetString("SmsUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States.
        /// </summary>
        public static string States {
            get {
                return ResourceManager.GetString("States", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudiceos.
        /// </summary>
        public static string SystemPageTitle {
            get {
                return ResourceManager.GetString("SystemPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string Translate {
            get {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Commercial Ads.
        /// </summary>
        public static string UserAds {
            get {
                return ResourceManager.GetString("UserAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Advertisements.
        /// </summary>
        public static string UserAdvertisement {
            get {
                return ResourceManager.GetString("UserAdvertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Title.
        /// </summary>
        public static string UserAdvertisementTitle {
            get {
                return ResourceManager.GetString("UserAdvertisementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Bundles.
        /// </summary>
        public static string UserBudles {
            get {
                return ResourceManager.GetString("UserBudles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        public static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Featured Ads.
        /// </summary>
        public static string UserFeaturedAds {
            get {
                return ResourceManager.GetString("UserFeaturedAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string UserFirstName {
            get {
                return ResourceManager.GetString("UserFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Name.
        /// </summary>
        public static string UserLastName {
            get {
                return ResourceManager.GetString("UserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users List.
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string UserPhone {
            get {
                return ResourceManager.GetString("UserPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserUserName {
            get {
                return ResourceManager.GetString("UserUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please don&apos;t Add a repeated Ads for the same product or the service that you has shared, All the repeated Ads will be deleted..
        /// </summary>
        public static string W_Add_Ad_Note {
            get {
                return ResourceManager.GetString("W_Add_Ad_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Advertisment.
        /// </summary>
        public static string W_AddAdvertisment {
            get {
                return ResourceManager.GetString("W-AddAdvertisment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisment Quick View.
        /// </summary>
        public static string W_AdQuickView {
            get {
                return ResourceManager.GetString("W-AdQuickView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        public static string W_AllCategories {
            get {
                return ResourceManager.GetString("W-AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved to Saudiceos.
        /// </summary>
        public static string W_AllRightsReserved {
            get {
                return ResourceManager.GetString("W-AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Category.
        /// </summary>
        public static string W_ChooseCategory {
            get {
                return ResourceManager.GetString("W-ChooseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose City.
        /// </summary>
        public static string W_ChooseCity {
            get {
                return ResourceManager.GetString("W-ChooseCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string W_ContactUs {
            get {
                return ResourceManager.GetString("W-ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string W_Download {
            get {
                return ResourceManager.GetString("W-Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download applicaion for free.
        /// </summary>
        public static string W_DownloadApp {
            get {
                return ResourceManager.GetString("W-DownloadApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string W_EditPRofile {
            get {
                return ResourceManager.GetString("W-EditPRofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite List.
        /// </summary>
        public static string W_Favorite {
            get {
                return ResourceManager.GetString("W-Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Advertisments.
        /// </summary>
        public static string W_FeaturedAds {
            get {
                return ResourceManager.GetString("W-FeaturedAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Consumed Your Free Ads This Month.
        /// </summary>
        public static string W_haveNoFreeAds {
            get {
                return ResourceManager.GetString("W-haveNoFreeAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string W_HomePage {
            get {
                return ResourceManager.GetString("W-HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Advertisments.
        /// </summary>
        public static string W_LatestAds {
            get {
                return ResourceManager.GetString("W-LatestAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string W_Login {
            get {
                return ResourceManager.GetString("W-Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string W_Login_Facebook {
            get {
                return ResourceManager.GetString("W-Login-Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password ?.
        /// </summary>
        public static string W_Login_ForgetPassoword {
            get {
                return ResourceManager.GetString("W-Login-ForgetPassoword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Plus.
        /// </summary>
        public static string W_Login_GooglePlus {
            get {
                return ResourceManager.GetString("W-Login-GooglePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or Login With.
        /// </summary>
        public static string W_Login_OrLoginWith {
            get {
                return ResourceManager.GetString("W-Login-OrLoginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remmember Me.
        /// </summary>
        public static string W_Login_RemmemberMe {
            get {
                return ResourceManager.GetString("W-Login-RemmemberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Ads.
        /// </summary>
        public static string W_MyAds {
            get {
                return ResourceManager.GetString("W-MyAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies Ads.
        /// </summary>
        public static string W_Offers {
            get {
                return ResourceManager.GetString("W-Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Ad.
        /// </summary>
        public static string W_PostAd {
            get {
                return ResourceManager.GetString("W_PostAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string W_PrivacyPolicy {
            get {
                return ResourceManager.GetString("W-PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string W_Register {
            get {
                return ResourceManager.GetString("W-Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype Password.
        /// </summary>
        public static string W_Register_ConfirmPassword {
            get {
                return ResourceManager.GetString("W-Register-ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string W_Register_Logout {
            get {
                return ResourceManager.GetString("W-Register-Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string W_Register_Password {
            get {
                return ResourceManager.GetString("W-Register-Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string W_Register_Phone {
            get {
                return ResourceManager.GetString("W-Register-Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string W_Register_Registeration {
            get {
                return ResourceManager.GetString("W-Register-Registeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login - Register.
        /// </summary>
        public static string W_Register_RegisterationOrLogin {
            get {
                return ResourceManager.GetString("W-Register-RegisterationOrLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Country.
        /// </summary>
        public static string W_Registeration_Country {
            get {
                return ResourceManager.GetString("W_Registeration_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Required.
        /// </summary>
        public static string W_Registeration_Country_Required {
            get {
                return ResourceManager.GetString("W_Registeration_Country_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string W_Registeration_FirstName {
            get {
                return ResourceManager.GetString("W_Registeration_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name Requried.
        /// </summary>
        public static string W_Registeration_FirstName_Required {
            get {
                return ResourceManager.GetString("W_Registeration_FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        public static string W_Registeration_Password {
            get {
                return ResourceManager.GetString("W_Registeration_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password Required.
        /// </summary>
        public static string W_Registeration_Password_Confirm {
            get {
                return ResourceManager.GetString("W_Registeration_Password_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confrmation Don&apos;t Match the password.
        /// </summary>
        public static string W_Registeration_Password_DonMatch {
            get {
                return ResourceManager.GetString("W_Registeration_Password_DonMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Required.
        /// </summary>
        public static string W_Registeration_Password_Required {
            get {
                return ResourceManager.GetString("W_Registeration_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password Required.
        /// </summary>
        public static string W_Registeration_PasswordConfirm_Required {
            get {
                return ResourceManager.GetString("W_Registeration_PasswordConfirm_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Not Valid.
        /// </summary>
        public static string W_Registeration_PasswordNotvalid {
            get {
                return ResourceManager.GetString("W_Registeration_PasswordNotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be {1} or more charcters.
        /// </summary>
        public static string W_Registeration_PasswordNotValid_Required {
            get {
                return ResourceManager.GetString("W_Registeration_PasswordNotValid_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number is not valid, Please use numbers only.
        /// </summary>
        public static string W_Registeration_Phone_NotValid {
            get {
                return ResourceManager.GetString("W_Registeration_Phone_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Required.
        /// </summary>
        public static string W_Registeration_Phone_Required {
            get {
                return ResourceManager.GetString("W_Registeration_Phone_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is too short, please check the number.
        /// </summary>
        public static string W_Registeration_Phone_Short {
            get {
                return ResourceManager.GetString("W_Registeration_Phone_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Name.
        /// </summary>
        public static string W_Registeration_SecondName {
            get {
                return ResourceManager.GetString("W_Registeration_SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Name Required.
        /// </summary>
        public static string W_Registeration_SecondName_Required {
            get {
                return ResourceManager.GetString("W_Registeration_SecondName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saftey Rules.
        /// </summary>
        public static string W_SafetyRules {
            get {
                return ResourceManager.GetString("W-SafetyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string W_SearchButton {
            get {
                return ResourceManager.GetString("W-SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for what you want.
        /// </summary>
        public static string W_SearchForWhat {
            get {
                return ResourceManager.GetString("W_SearchForWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string W_Settings {
            get {
                return ResourceManager.GetString("W-Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of use.
        /// </summary>
        public static string W_UseTerms {
            get {
                return ResourceManager.GetString("W-UseTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Ad Added Successfully.
        /// </summary>
        public static string WAddedSuccessfully {
            get {
                return ResourceManager.GetString("WAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisment Quick Details.
        /// </summary>
        public static string WAdDetails {
            get {
                return ResourceManager.GetString("WAdDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete all the required fields.
        /// </summary>
        public static string WMakeSureCompleteData {
            get {
                return ResourceManager.GetString("WMakeSureCompleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string WNext {
            get {
                return ResourceManager.GetString("WNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one photo required.
        /// </summary>
        public static string WPleaseAddPhoto {
            get {
                return ResourceManager.GetString("WPleaseAddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string WPrev {
            get {
                return ResourceManager.GetString("WPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pleash refresh the page and try again.
        /// </summary>
        public static string WRefreshPage {
            get {
                return ResourceManager.GetString("WRefreshPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string WSave {
            get {
                return ResourceManager.GetString("WSave", resourceCulture);
            }
        }
    }
}
